// Functions

function getComputerChoice() {
  const choices = ["rock", "paper", "scissors"];
  return choices[Math.floor(Math.random() * choices.length)];
} // Use Math.random to make a random computer choice

function playRound(playerSelection) {
  let computerSelection = getComputerChoice();
  let computerPoint = 0;
  let playerPoint = 0;
  let result = "";
  if (playerSelection === computerSelection) {
    result = "draw";
  } else if (
    (playerSelection === "rock" && computerSelection === "scissors") ||
    (playerSelection === "scissors" && computerSelection === "paper") ||
    (playerSelection === "paper" && computerSelection === "rock")
  ) {
    result = "win";
    playerPoint += 1;
  } else {
    result = "lose";
    computerPoint += 1;
  }
  updateResult(
    playerSelection,
    computerSelection,
    result,
    computerPoint,
    playerPoint
  );
} // Uses input from button to compare it to the computerSelection generated by getComputerChoice function

function updateResult(
  playerSelection,
  computerSelection,
  result,
  computerPoint,
  playerPoint
) {
  computerScore += computerPoint;
  playerScore += playerPoint;
  scoreWindow.innerHTML = `<span class="score">Score</span><br><i class="fa-solid fa-user"></i> ${playerScore}<br><i class="fa-solid fa-robot"></i> ${computerScore}`;
  resultWindow.innerHTML = `<i class="fa-solid fa-user"></i> ${playerSelection}.<br><i class="fa-solid fa-robot"></i> ${computerSelection}.<br><span class="result">You ${result}!</span>`;
  scoreAndResult.appendChild(resultWindow);
} // Create a new div to display output of playRound function

// Variables
const container = document.querySelector(".container");
const scoreAndResult = document.querySelector(".score-and-result");
const resultWindow = document.querySelector(".result-window");
const scoreWindow = document.querySelector(".score-window");
let playerScore = 0;
let computerScore = 0;

// Event listener
const rock = document.querySelector("#rock");
const paper = document.querySelector("#paper");
const scissors = document.querySelector("#scissors");

rock.addEventListener("click", () => {
  playRound("rock");
});
paper.addEventListener("click", () => {
  playRound("paper");
});
scissors.addEventListener("click", () => {
  playRound("scissors");
});
